### PR TITLE
Invalid changeUrl when change number is null

### PR DESCRIPTION
**Pull request by djarosz**

### CODE REVIEW

**Comment by MichaelSims** [comment]
What exactly is the issue? (Also, I'm assuming you meant "patch set number" instead of "change number" based on the diff.) If it's a trailing `/` in the URL, those are typically ignored by most URL "routers", including my installation of Gerrit. I could be missing something though.

**Comment by djarosz** [comment]
Yes I meant patch set number. 

Case of null patch set number generated  change url is actually http://server:8976/1/null and not http://server:8976/1/ as I expected before.

**Comment by djarosz** [comment]
But maybe it can be done with simpler (?) expression 

```
     "$baseUrl/$changeNumber/${patchSetNumber?.toString().orEmpty()}"
```

**Comment by MichaelSims** [comment]
Thanks for explaining the issue, I see now. I had originally thought of using something like your `orEmpty()` suggestion but decided ultimately to go with a joinToString approach where we also drop the trailing slash if the patch set number is missing: https://github.com/MichaelSims/gerrit-slack-bot/commit/84c0c44e81e5f75f4b7c09bd183045e5cad0728d   I've made a 3.0.1 release with that fix. Thanks!

**Pull request closed without merging**
